export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REQUEST_FAILURE = 'AUTH_REQUEST_FAILURE';
