// Fetch all locations action types
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_REQUEST = 'FETCH_LOCATIONS_REQUEST';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

// Fetch location details action types
export const FETCH_LOCATION_DETAILS_REQUEST = 'FETCH_LOCATION_DETAILS_REQUEST';
export const FETCH_LOCATION_DETAILS_SUCCESS = 'FETCH_LOCATION_DETAILS_SUCCESS';
export const FETCH_LOCATION_DETAILS_FAILURE = 'FETCH_LOCATION_DETAILS_FAILURE';
